Repository paparazzi/pprzlink, pull requests merged in 2020-06, with the labels that each got.

#115 Gvf parametric
  message_definitions/v1.0/messages.xml
Labels: new message

#112 [c_standalone] add user_data in rx init and callback
  README.md
  tools/generator/C/include_v2.0/pprzlink_standalone.h
Labels: enhancement

#116 Using logging module instead of raw print statements
  lib/v1.0/python/pprzlink/ivy.py
  lib/v1.0/python/pprzlink/messages_xml_map.py
  lib/v1.0/python/pprzlink/pprz_transport.py
  lib/v1.0/python/pprzlink/serial.py
  lib/v1.0/python/pprzlink/udp.py
  lib/v2.0/python/pprzlink/ivy.py
  lib/v2.0/python/pprzlink/messages_xml_map.py
  lib/v2.0/python/pprzlink/pprz_transport.py
  lib/v2.0/python/pprzlink/serial.py
  lib/v2.0/python/pprzlink/udp.py
Labels: enhancement

#111 fix encoding of payload to ivy string format
  lib/v2.0/python/pprzlink/message.py
Labels: bug
